version: 2
jobs:
   build:
     branches:
        ignore:
          - /deploy-.*/
     docker:
       - image: circleci/node:lts
     steps:
       - checkout
       - run: npm i
       - run: npx proton-pack
       - run: npm run lint
       - run: npm test
       - run: npm run i18n:validate
       - run: npm run i18n:validate:context